### ISSUE TITLE
Fehler: Programmstart von gdalwarp schlug fehl

### ISSUE THREAD

**Issue by Johannes83** [gdi-by/downloadclient#110]
Download von folgendem Dienst:
http://www.geodaten.bayern.de/inspire/dls/dop200.xml

Variante EPSG:31468 image/tiff

Weiterverarbeitung: Konvertierung nach GeoTiff in ETRS8 UTM Zone32n
![Error](https://user-images.githubusercontent.com/49948778/56661724-a32ed000-66a2-11e9-90af-f1e6ca975d91.JPG)

**Comment by LuciaBirk** [comment]
Im Zuge der Umstellung des Bezugssystems auf UTM im Laufe dieses Jahres (?) dringend.

**Comment by gdi-by** [comment]
Vorbereitungen für neues Release Ende Mai 2019 laufen. Darin kann Fehler derzeit nicht nachreproduziert werden. Selbe Einstellungen gemäß obigen Screenshot verwendet.
Issue bleibt noch offen und wird mit Release geschlossen.

**Comment by gdi-by** [comment]
behoben mit version 1.2.0
