### ISSUE TITLE
GmlEmptyCheckJob berücksichtigt keine große Dateien

### ISSUE THREAD

**Issue by JuergenWeichand** [gdi-by/downloadclient#134]
[LDBV] Bei WFS-Responses im Bereich > 1 GB dauert der `GmlEmptyCheckJob.java` auf unseren Testrechnern bis zu 30min. Im Gegensatz zum `GMLCheckJob.java` werden sehr große XML-Dateien nichts besonders berücksichtigt. 

Idealweise werden mit einem Streaming-Parser nur die ersten 1000 Zeilen ausgewertet, um das Vorhandensein von Objekten zu verifizieren. 

Während der Ausführung des GmlEmptyCheckJob ist die Oberfläche des DLC nicht gesperrt wodurch Folgefehler entstehen können. 

Viele Grüße
Jürgen

**Comment by gdi-by** [comment]
Umsetzung erfolgt bereits mit Release 1.2.2.

**Comment by gdi-by** [comment]
Issue wurde mit Release 1.2.2 behoben.
