### ISSUE TITLE
GUI startet nicht

### ISSUE THREAD

**Issue by MarshalMappers** [gdi-by/downloadclient#135]
Hallo zusammen, 
Mein Betriebssystem ist Windows 10.
Ich habe die Java Version 11 installiert, inklusive path-Eintrag und JAVA_HOME eintrag. 
Weiterhin die Version 1.2.1 udn 1.2.0 für die Java Version 11 Heruntergeladen und entzippt. 
Durch Ausführen der Datei startup.bat öffnet sich die GUI leider nicht. Durch Ausführen als Administrator erhalte ich die Fehlermeldung: Error: Unable to access jarfile downloadclient.jar.

Proxy Einstellungen habe ich nicht verändert. 
Mein Antivirusprogramm habe ich auch zu Testzwecken deaktiviert. Das hat leider auch nichts geholfen.

Wäre schön, wenn mir jemand weiterhelfen könnte.

**Comment by gdi-by** [comment]
Guten Tag,

danke für die Meldung. Das Problem ist bereits bekannt und wird voraussichtlich mit dem nächsten Release gefixt.
Bis dahin kann der DLC unter Java 11 folgendermaßen gestartet werden:

Für die Ausführung des Download-Clients mit Java 11.0 wird JavaFX benötigt:
- OpenJDK-basierte Java Versionen *mit* JavaFX:
    - Liberica JDK (8 und 11): https://bell-sw.com/ (JavaFX enthalten)
    - Zulu JDK (8 und 11): https://www.azul.com/downloads/zulu-community/ (JavaFX enthalten)
- OpenJDK-basierte Java Versionen *ohne* JavaFX:
    - AdoptOpenJDK (8 und 11): https://adoptopenjdk.net/ (JavaFX **nicht** enthalten)
    - Amazon Corretto (8 und 11): https://docs.aws.amazon.com/corretto/ (JavaFX **nicht** enthalten)
--Für diese beiden Java Versionen muss zusätzlich das passende `JavaFX-SDK <https://openjfx.io>`_ installiert sein.


Passen Sie anschließend die startup.bat an:

start javaw **--module-path _\<PATH\>_\javafx-sdk-11.0.2\lib --add-modules javafx.controls,javafx.fxml,javafx.web** -jar downloadclient.jar -config=config

Ich hoffe, wir konnten Ihnen damit weiterhelfen.

gdi-by

**Comment by MarshalMappers** [comment]
Hallo zusammen,
leider komme ich nicht weiter.
Die beiden OpenJDK-basierten Java Versionen mit JavaFX enthalten keinen Pfad zu \javafx-sdk-11.0.2\lib.
Installiert wurde nun das AdoptOpenJDK 11 sowie der Pfad der Umgebungsvariable angepasst. Weiterhin wurde das passende JavaFX-SDK <https://openjfx.io> heruntergeladen. Soweit ich verstehe, kann das nicht installiert werden, sondern muss lediglich entpackt werden. Ist das soweit richtig? Muss es an eine entsprechende Stelle entpackt werden?
Müssen in der Config noch Anpassungen vorgenommen werden?

Vielen Dank und Beste Grüße

Marcel Beckmann

**Comment by gdi-by** [comment]
Guten Tag Herr Beckmann,

Sie haben das soweit korrekt zusammengefasst.
Achten Sie aber darauf, dass der DLC die Berechtigung hat, auf javafx zuzugreifen. Eventuell ist der Zugriff auf den von Ihnen genutzten Speicherort beschränkt.

Geben Sie in der startup.bat den vollständigen Pfad zu javafx an (z.B.):
start javaw --module-path **C:\Temp\javafx-sdk-11.0.2\lib** --add-modules javafx.controls,javafx.fxml,javafx.web -jar downloadclient.jar -config=config

Anpassungen an der Config sind nicht vorzunehmen. Falls Sie einen Proxy-Server nutzen, müssen Sie aber eine proxy.xml anlegen (siehe config\proxy.xml.sample).


Viele Grüße
gdi-by

**Comment by MarshalMappers** [comment]
Hallo zusammen,

javafx habe ich nun in den Ordner C:\Temp verschoben. Die GUI startet nun, allerdings bekomme ich davor noch folgende Fehlermeldung: WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

Ich weiß jetzt nicht, ob das normal ist. Ich werde die GUI nun testen. Bei Bedarf melde ich mich wieder. 

Vielen Dank und beste Grüße

Marcel Beckmann

**Comment by gdi-by** [comment]
Hallo Herr Beckmann,

es freut mich, dass der DLC nun läuft.
Die von Ihnen gemeldete Fehlermeldung ist normal und erscheint meines Wissens, wenn sie die Logausgabe in der startup.bat aktivieren:

Ohne Log-Ausgabe:
start java**w** --module-path ...

Mit Log-Ausgabe:
start java --module-path ...

Wenn Sie keine weitere Unterstützung mehr benötigen, werden wir das Issue in ~1 Woche schließen.

Viele Grüße
gdi-by

**Comment by gdi-by** [comment]
Nach Wartezeit geschlossen.
