### ISSUE TITLE
Benutzerdefinierte Erweiterung der Verarbeitungskonfiguration und Mimetypes nicht möglich

### ISSUE THREAD

**Issue by gdi-by** [gdi-by/downloadclient#37]
Die Anpassung / Erweiterung der Verarbeitungskonfiguration sowie der Mimetypes in der Datei verarbeitungsschritte.xml bzw. mimetypes.xml im Ordner config hat keine Auswirkungen, da der Download-Client offensichtlich beim Start nicht auf diese Datei zugreift.

**Comment by dmth** [comment]
Das ist korrekt, ich vermute die folgenden Änderungen rufen dies hervor:

Verarbeitungs-Konfiguration:
https://github.com/gdi-by/downloadclient/pull/34/files#diff-c80b1d790db165f4b41ac4dfc44129c6R51

MIME-Types:
https://github.com/gdi-by/downloadclient/pull/34/files#diff-29848554717453819eddd970594936e9R51

Hier wurde der Code auf die gebündelte `.jar` Datei angepasst.

**Comment by dmth** [comment]
Der heutige PR löst diese Problem.
