### ISSUE TITLE
Einbindung eines WMS für das Kartenfenster schlägt fehl (falsche Projektion).

### ISSUE THREAD

**Issue by gdi-by** [gdi-by/downloadclient#38]
Standardmäßig greift das Kartenfenster über WMS auf den WebAtlasDE (BKG) in Graustufen zu. Bei Einbindung eines anderen WMS für die Hintergrundkarte über die Konfigurationsdatei `serviceSetting.xml` entsteht ein Fehler in der Projektion ("Bayern fällt spiegelverkehrt um" - vgl. Bild).

![donwloadclient-kartenbild](https://cloud.githubusercontent.com/assets/13452857/19149313/80c8dc04-8bc1-11e6-89e0-9b9bf4f30e25.png)

**Comment by dmth** [comment]
Aktuell sind wir dabei dieses Fehler zu lösen. Wir schätzen, dass ein Lösung Ende März 2017 im Downloadclient bereit stehen wird.

**Comment by dmth** [comment]
Mit https://github.com/gdi-by/downloadclient/pull/54 wird dieser Fehler korrigiert.

**Comment by gdi-by** [comment]
Ticket bleibt noch offen, bis finale Lösung erfolgt ist.

**Comment by gdi-by** [comment]
Ursprünglicher Bug gelöst. Noch dabei beobachteter Bug isoliert in #76 neu gestellt
