### ISSUE TITLE
Suche über eingebundenen Metadaten-Katalog funktioniert nicht.

### ISSUE THREAD

**Issue by gdi-by** [gdi-by/downloadclient#42]
Getestet: In serviceSettings unter settings\services\catalogues\catalog\url folgende CSW-URL eingetragen:  
https://apps.geoportal.nrw.de/soapServices/CSWStartup?service=CSW&amp;request=GetCapabilities

Ergebnis: Download-Client startet ohne Fehlermeldung. Eingabe eines Suchbegriffs führt auch nach mehreren Minuten zu keinem Treffer (Meldung "Frage Infos beim Dienst an" in der GUI).

Vermutung: Download-Client scheint auf die URL aus dem ersten, in den Capabilities bei der Operation "GetRecords" angeführten ows:Post Element zuzugreifen. Dieses enthält im Falle des o.a. CSW keine XML-Post-URL, sondern eine SOAP-Post-URL (s. https://apps.geoportal.nrw.de/soapServices/CSWStartup?service=CSW&request=GetCapabilities), mit der die CSW-SearchQuery (https://github.com/gdi-by/downloadclient/blob/master/src/resources/csw_searchQuery.xml) nicht funktioniert.

Mit diesem CSW funktioniert die Suche: http://isk.geobasis-bb.de/geomis-csw/service?Request=GetCapabilities&Service=CSW

**Comment by JuergenWeichand** [comment]
Wird mit Übernahme von https://github.com/gdi-by/downloadclient/pull/45 behoben.

**Comment by gdi-by** [comment]
Vielen Dank. Bugfix wurde gemerged. 
Steht ab Version >=  `1.1.0` zur Verfügung.
