### ISSUE TITLE
Download mehrerer Varianten eines mehrteiligen Datensatzes

### ISSUE THREAD

**Issue by ruester** [gdi-by/downloadclient#47]
Möchte man eine andere Variante eines mehrteiligen Datensatzes herunterladen, so wird immer die erste Variante heruntergeladen.

Folgender INSPIRE Atom Feed wurde getestet:
http://geoportal.geoportal-th.de/dienste/atom_th_dtk100

Wählt man dort die zweite Variante (Einzelebenen in Shape-Dateien) im Download Client aus werden trotzdem die TIFF-Dateien heruntergeladen (erste Variante).

**Comment by gdi-by** [comment]
Das beschriebene Verhalten konnte nachvollzogend werden.

Wahrscheinliche Ursache: Die beiden `entry` Elemente des Dataset Feeds, die die beiden Datensatz-Varianten in den o.g. Formaten bereitstellen, haben dieselbe `id` (s. http://geoportal.geoportal-th.de/dienste/atom_th_dtk100?type=dataset&id=ec66d74d-52ec-4413-98a6-ef262090aaec). Hier sollte für jede Variante ein eindeutiger HTTP URI verwendet werden.
Bei Entries mit unterschiedlichen ids wird die ausgewählte Variante korrekt herunter geladen (Bsp.: https://geoportal.bayern.de/gdiadmin/ausgabe/ATOM_DATASET/d408a036-9c71-4682-8391-67ff729d890d)

**Comment by ruester** [comment]
Vielen Dank für die schnelle Rückmeldung!
Der Fehler liegt also beim Dienst...
