### ISSUE TITLE
Unvollständige MimeTypes-Liste

### ISSUE THREAD

**Issue by JuergenWeichand** [gdi-by/downloadclient#49]
Die implementierte MimeTypes-Liste ist nicht vollständig https://github.com/gdi-by/downloadclient/blob/master/src/resources/de/bayern/gdi/model/mimetypes.xml

Diese sollte mindestens alle MimeTypes aus http://inspire.ec.europa.eu/media-types/ (Referenz in den TG-DLS 3.1) enthalten.

Hierdurch wird beispielsweise für `application/x-shapefile` die Dateiendung `.gml` vergeben.

**Comment by gdi-by** [comment]
Erweiterte MimeTypes-Liste wird von gdi-by bereitgestellt.

**Comment by gdi-by** [comment]
Vergabe der prio 1

**Comment by gdi-by** [comment]
Prüfung läuft derzeit noch

**Comment by gdi-by** [comment]
MimeType Liste mit Release 1.1.0 aktualisiert
