### ISSUE TITLE
Nutzung der Oberfläche zum Editieren und Ausführen einer gespeicherten Konfiguration

### ISSUE THREAD

**Issue by dmth** [gdi-by/downloadclient#57]
Der Downloadclient ermöglicht das Erstellen und Abspeichern einer Downloadkonfiguration. Allerdings ist es nicht möglich diese in der Oberfläche einzulesen und zu editieren.

Es ist ggfs. sinnvoll das folgende zu ermöglichen:
 * Laden von Downloadkonfigurationen
 * Ausführen der gelandenen Downloadkonfiguration
 * Ändern der Downloadkonfiguration
 * Speichern der geänderten Downloadkonfiguration

**Comment by gdi-by** [comment]
Umsetzung in einem nächsten Release geplant.

**Comment by dmth** [comment]
Besonders zu beachten sind beim Einladen der Daten, die möglichen Fehlerfälle
 * Umgang mit Pre-Defined Queries vom WFS:
 ** Was geschieht wenn der Server die Query nicht mehr anbietet?
 ** Was geschieht wenn der Server die Query mit anderen Attributen anbietet?

 * Umgang mit ATOM:
 ** Kann das herunter zu ladene Polygon  in der Karte gehighlighted werden?
 ** Was passiert wenn der Dienst die geladenen Daten nicht mehr anbietet?

**Comment by dmth** [comment]
Das Repository der Intevation enthält nun die Möglichkeit die gespeicherte Konfiguration zu editieren.

**Comment by dmth** [comment]
In https://github.com/gdi-by/downloadclient/pull/77 ist diese Änderung nun enthalten.

**Comment by gdi-by** [comment]
Verifziert mit PR #95 - Issue ist behoben und wird geschlossen.
