### ISSUE TITLE
Verbessertes Logging / Log-Historie / Status-Historie

### ISSUE THREAD

**Issue by dmth** [gdi-by/downloadclient#63]
Im Client wird aktuell immer nur der derzeitige Status in der Statuszeile angezeigt.
Die Oberfläche sollte um eine Historie von Status-Historie ergänzt werden aus der vorhergehende Meldungen ersichtlich sind.

**Comment by gdi-by** [comment]
Ergänzung: 
Ergebnis der Validierung der Kompatibilität des gewählten Verarbeitungsschritts zum gewählten Datenformat-Typ sollte in der Status-Zeile angezeigt und im Logfile dokumentiert werden. 
Siehe auch https://github.com/gdi-by/downloadclient-test/issues/14 und https://github.com/gdi-by/downloadclient/issues/62.

**Comment by gdi-by** [comment]
Umsetzung zusammen mit #62 für ein nächstes Release geplant

**Comment by gdi-by** [comment]
Beauftragt - Umsetzung zum 11.07.2017

**Comment by gdi-by** [comment]
Erfolgreich umgesetzt
