### ISSUE TITLE
GUI: Suchfeld besser kennzeichnen

### ISSUE THREAD

**Issue by gdi-by** [gdi-by/downloadclient#71]
Das Suchfeld besser als solches erkennbar machen, indem darüber eine Beschriftung "Dienst suchen" angebracht und im Feld ein hint "Ihr Suchbegriff (z.B. Naturschutz) angezeigt wird.

![gui_suchfeld](https://cloud.githubusercontent.com/assets/13452857/24510815/846a60d4-156a-11e7-9f95-fa189c13b219.jpg)

**Comment by jsaalfeld** [comment]
Über dem Suchfeld wird es einen Text "Dienst suchen". Im Suchfeld wird ein hint angezeigt werden. Neben dem Suchfeld wird eine Lupe erscheinen, die sich dort mit dem Spinner, der die aktive Suche anzeigt, abwechselt. Die Lupe wird dann angezeigt, wenn gerade nicht aktiv gesucht wird und der Spinner, wenn gerade eine Suche läuft. Als Suchsymbol werden die Unicode-Zeichen Verwendet (http://www.fileformat.info/info/unicode/char/1f50e/index.htm).

**Comment by dmth** [comment]
Mit https://github.com/Intevation/downloadclient/commit/f9002de4583ff23747937cd614244a227d18bd9c ist dies nun in unserem Entwicklungsrepository vorhanden. Screenshots folgen.

**Comment by awoestmann** [comment]
![downloadclient_prompt_text](https://cloud.githubusercontent.com/assets/20797843/25433722/af588044-2a89-11e7-839e-3b84be636650.png)
![downloadclient_spinner](https://cloud.githubusercontent.com/assets/20797843/25433728/b6d912ca-2a89-11e7-867a-7176ce3a68f8.png)

**Comment by dmth** [comment]
In https://github.com/gdi-by/downloadclient/pull/77 ist diese Änderung nun enthalten.

**Comment by gdi-by** [comment]
Erfolgreich umgesetzt - Issue geschlossen
