### ISSUE TITLE
HTTP-Timeout konfigurierbar gestalten

### ISSUE THREAD

**Issue by JuergenWeichand** [gdi-by/downloadclient#79]
[LDBV] Der HTTP-Timeout ist z. Z. hardcoded auf 10 Sekunden eingestellt. Dies gilt für alle Dienste und alle Operationen. 

Spezielle WFS-Dienste (z. B. Testserver mit 50.000.000 Objekten) erfordern bei komplexen GetFeature-Anfragen jedoch deutlich höhere Timeouts. 

Aus diesem Grund sollte der HTTP-Timeout grundsätzlich über die Konfiguration gesteuert werden können. 

* Variante 1: Der bisher feste HTTP-Timeout kann über die Konfiguration gesteuert werden.  

* Variante 2: Es werden in der Konfiguration zwei HTTP-Timeout-Parameter festgelegt. Ein globaler Parameter für alle HTTP-Anfragen (siehe Variante 1) ergänzt um einen Parameter speziell für die GetFeature-Anfrage bei WFS.

**Comment by dmth** [comment]
Sollen in Variante 2 die Parameter ebenfalls konfigurierbar sein?
Ich schlage vor diese Variante in ein eigenes Issue auszulagern.

**Comment by gdi-by** [comment]
Beauftragt - Umsetzung Variante 1 zum 11.07.2017

**Comment by jsaalfeld** [comment]
Wir würden vorschlagen diese Konfiguration in die https://github.com/gdi-by/downloadclient/blob/master/src/resources/serviceSetting.xml aufzunehmen. Diese würden wir durch die Erweiterung der Datei um "Applikationseinstellungen" jedoch gern zu "settings.xml" umbenennen. Sie würde dann folgende Form haben

```
<settings>
	<catalogues>
		<catalog>
			<name>CSW GDI-BY</name>
			<url>http://geoportal.bayern.de/csw/gdi?service=CSW&amp;request=GetCapabilities</url>
		</catalog>
	</catalogues>
	<wms>
		<service>
			<name>WMS WebAtlasDE.light Graustufen</name>
			<url>http://sg.geodatenzentrum.de/wms_webatlasde.light_grau</url>
			<layer>webatlasde.light_grau</layer>
			<source>© GeoBasis-DE / BKG </source>
		</service>
	</wms>
	<services></services>
	<application>
                <requestTimeout_s>35</requestTimeout_s>
        </application>
</settings>
```

Die Umbennenung hält Wege für zukünftige Anpassungen in der Konfiguration offen und lässt Konfiguration zentral, in einer Datei; was ein Vorteil für den Nutzer, die Wartbarkeit und Administration der Anwendung ist.

**Comment by dmth** [comment]
Gibt es zu der Umbenennung von ServiceSettings.xml zu settings.xml Fragen oder Anmerkungen? Wenn nicht würden wir das in der kommenden Woche machen.

**Comment by gdi-by** [comment]
Werden evtl. Fragen oder Anmerkungen bis spätestens 05.07.17 10:00 Uhr mitteilen.

**Comment by gdi-by** [comment]
Keine Bedenken hinsichtlich der Umbenennung. 

XML-Deklaration sollte enthalten sein mit Angabe des Encoding.
                                          
`<?xml` version="1.0" encoding="UTF-8" `?>`

**Comment by dmth** [comment]
> Keine Bedenken hinsichtlich der Umbenennung.

OK, danke für die schnelle Rückmeldung. Wir machen dann mal weiter.


> XML-Deklaration sollte enthalten sein mit Angabe des Encoding.
> `<?xml version="1.0" encoding="UTF-8" ?>`

Ist das sinnvoll? Ich würde in diesem Fall als Nutzer erwarten, dass ich die Konfiguration auch in einem anderen Encoding schreiben kann und das dann angebe.
Ich weiß nicht ob der Client das dann auch lesen und interpretieren kann.

**Comment by awoestmann** [comment]
Wurde mit https://github.com/Intevation/downloadclient/commit/bc1e1809e640e1106229c6c27bce7705a264d061 umgesetzt und wird mit dem nächsten Pull Request ausgeliefert.

**Comment by dmth** [comment]
Mit https://github.com/gdi-by/downloadclient/pull/84 steht dies nun zur Verfügung

**Comment by gdi-by** [comment]
Verifziert mit PR #88. 
Gefixed. Verbesserungsvorschlag erfasst in https://github.com/gdi-by/downloadclient/issues/89
Issue #79 wird geschlossen.
