### ISSUE TITLE
WFS-Anfragen mit Paging werden nicht mehr ausgeführt

### ISSUE THREAD

**Issue by gdi-by** [gdi-by/downloadclient#97]
Beim Download von Daten über WFS wird zunächst geprüft, ob die vollständige Ergebnismenge in einer Abfrage heruntergeladen werden kann (`resultType=hits`). Sofern dies möglich ist wird der Abruf korrekt ausgeführt. Werden jedoch mehrere Portionen benötigt bleibt der DownloadClient mit der Nachricht „Download startet“ hängen.

Beispiel: http://geoserv.weichand.de:8080/geoserver/wfs?service=wfs&acceptversions=2.0.0&request=GetCapabilities

Abruf aller Regierungsbezirke -> Paging wird NICHT benötigt -> Abruf funktioniert
Abruf aller Gemeinden -> Paging wird benötigt -> Keine Reaktion, es wird kein GetFeature-Request ausgeführt.

**Comment by gdi-by** [comment]
@BjoernSchilberg #94 hat das Problem nicht gelöst (Anmerkung - es wurde ein HTTP-Proxy verwendet).

**Comment by s-l-teichmann** [comment]
Noch einmal ohne Proxy (`mvn exec:java`) und mit Proxy (`mvn -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080 exec:java`) getest. Funktioniert beides.

Manuell eine `config/proxy.xml` angelegt:
```<?xml version="1.0" encoding="UTF-8"?>
<ProxyConfiguration overrideSystemSettings="true" enableSNIExtension="true">
    <HTTPProxyHost>localhost</HTTPProxyHost>
    <HTTPProxyPort>8080</HTTPProxyPort>
</ProxyConfiguration>
```
und mit `mvn exec:java -Dexec.args="--config config"` gestartet. Funktioniert ebenfalls.
Die Log-Ausgaben des Proxys zeugen davon, dass er auch benutzt wird.

Hier muss also noch ein anderes Problem vorliegen, das ich noch nicht reproduzieren kann.

**Comment by BjoernSchilberg** [comment]
Obige Test von @s-l-teichmann mit gdi-by@9606a911594e8b3cc3495186c9e8cb93454532c1 wiederholt. Beobachtungen von@gdi-by konnte nicht  nachvollzogen werden. Gebenfalls wäre weitere Infos interessant.
